### PR TITLE
Fix: `nys-button` duplicate onClick event

### LINKED ISSUE #1022: BUG: `nys-button` executes onclick twice
## Summary
When using `nys-button` in vanilla JavaScript, assigning an inline onclick handler (e.g., onclick="..." ) causes the handler to execute twice per click.

## Context & Behavior:

- Vanilla JS: onclick triggers twice.
Works correctly when using addEventListener("nys-click", ...) instead.

- React: No duplication issue, since React requires using custom event props (e.g., `nNysClick`) instead of `onClick`. However, onClick does not work at all (likely not intended).

- Lit.dev / Storybook: Works correctly -> `@nys-click` behaves as expected.

Example:
```
<nys-button id="translateBtn1" name="translate" onClick="openTranslate();"></nys-button>

// VS

<nys-button id="translateBtn2" name="translate"></nys-button>

<script>
    function openTranslate() {
      alert("opening");
      console.log("opening");
    };


  const btn = document.getElementById("translateBtn2");
  btn.addEventListener("nys-click", () => {
    alert("opening");
    console.log("opening");
  });
</script>
```

### PR DESCRIPTION
**Pull request by NovaCat35**
# Summary

Resolve issue with `nys-button`'s `onClick` executing click button twice + WTR test.

## Breaking change

This is **not** a breaking change.  

## Related issues

Closes #1022 🎟️

## Testing and review
I have tested on vanilla JS demo, React Demo, and Storybook with the following conditions:

### Vanilla JS
- addEventListener("nys-click")
- `onClick` prop
```
<nys-button id="translateBtn1" name="translate" onClick="openTranslate();"></nys-button>

// VS

<nys-button id="translateBtn2" name="translate"></nys-button>

<script>
    function openTranslate() {
      alert("opening");
      console.log("opening");
    };


  const btn = document.getElementById("translateBtn2");
  btn.addEventListener("nys-click", () => {
    alert("opening");
    console.log("opening");
  });
</script>

// VS

<nys-button
   id="translateBtn3"
   label="Translate"
 ></nys-button>
      
<script>
     // Testing by utilizing the prop onClick
    const btn = document.getElementById('translateBtn3');
    btn.onClick = () => openTranslate();
</script>
```

### React
- The `onClick` prop
- The custom React/Lit.dev preset prop `onNysClick`
```
// nysds-components.ts
export const NysButtonComponent = createComponent({
  react: React,
  tagName: "nys-button",
  elementClass: NysButton,
  events: {
    onNysClick: "nys-click",
    onNysFocus: "nys-focus",
    onNysBlur: "nys-blur",
  },
});

...
// form.ts
        <NysButtonComponent
          label="Testing"
          onNysClick={toDoFunction}
        />
```

### Storybook
- `@nys-click`
- `@click`

### CODE REVIEW

File: packages/nys-button/src/nys-button.ts [hunk 1]
```diff
@@ -135,7 +136,7 @@ export class NysButton extends LitElement {
 
   private _manageFormAction() {
     // If an onClick function is provided, call it
-    if (typeof this.onClick === "function") {
+    if (typeof this.onClick === "function" && this.onClick !== null) {
```
Comment (esteinborn) [inline packages/nys-button/src/nys-button.ts]: is "function" a valid `typeof`? or is this different from typescript typing?
