### PR TITLE
Fix: checkbox description bug

### LINKED ISSUE #1198: BUG: clicking description of `nys-checkbox` won't toggle the checkbox
## Summary
Clicking the description of the `nys-checkbox` won't toggle it. Please fix the issue and confirm for both the normal description and the slotted ones.

### PR DESCRIPTION
**Pull request by NovaCat35**
# Summary

Fixed bug where clicking the description of the nys-checkbox won't toggle it. Confirm for both the normal description and the slotted ones.

## Breaking change

This is **not** a breaking change.  

## Related issues

Closes #1198 🎟️

### CODE REVIEW

File: packages/nys-checkbox/src/nys-checkbox.ts [hunk 1]
```diff
@@ -8,9 +8,8 @@ import styles from "./nys-checkbox.scss?inline";
 let checkboxIdCounter = 0; // Counter for generating unique IDs
 
 /**
- * `<nys-checkbox>` is a form-associated, accessible checkbox component.
- * Supports validation, labels, error messages, and keyboard interaction.
- * Can exist independently or inside a `<nys-checkboxgroup>`.
+ * `<nys-checkbox>` is a form-associated, accessible checkbox co88133
```
Comment (emilygorelik) [inline packages/nys-checkbox/src/nys-checkbox.ts]: co88133??

**Review by emilygorelik — DISMISSED** [review]
fix the comment, otherwise LGTM
