### PR TITLE
Doc/Fix: enhance dispatch events + accordion fix

### LINKED ISSUE #796: Documentation: DispatchEvents and their details
We need to make sure that the dispatchEvents and their details are correctly documented on the storybook and reference site.

### LINKED ISSUE #836: Bug: `nys-accordion` won't open on ref site
The `nys-accordion` won't toggle the expand on reference site

### PR DESCRIPTION
**Pull request by NovaCat35**
# Summary

- This PR adds documentation to the hidden dispatch events `detail` object and what they bubble up.  
**‼️ Going forward, please follow this format for the event section.**

- This PR also fixes the accordion issue with slots not being updated for static sites like 11.ty

## Breaking change

⚠️ This is a **potential** a breaking change upstream. 
Reason: dispatch event for `nys-alert` changed from `nys-alert-closed` to `nys-close`
@esteinborn please announce this change in the next release

## Related issues

Closes #796 🎟️
Closes #836 🎟️

## Dependent Issues
Need to complete this ticket for reference site https://github.com/ITS-HCD/nysds-site/issues/233 🎟️ when this PR is merged

## Screenshots
This is what the new documentation looks like:
Screenshot 2025-08-22 at 11 22 58 AM

### CODE REVIEW

File: packages/nys-textarea/src/nys-textarea.ts [hunk 1]
```diff
@@ -233,7 +233,7 @@ export class NysTextarea extends LitElement {
     this.value = select.value;
     this.dispatchEvent(
       new CustomEvent("selectionchange", {
```
Comment (emilygorelik) [inline packages/nys-textarea/src/nys-textarea.ts:235]: custom event needs `nys-` prefix, no?

File: packages/nys-backtotop/src/nys-backtotop.mdx [hunk 2]
```diff
@@ -72,36 +72,6 @@ The `nys-backtotop` component includes the following accessibility-focused featu
 - Pressing `Enter` or `Space` activates the backtotop functionality
 - Visible only when the user scrolls down the page, ensuring it does not distract from the content
 
-## Events
```
Comment (emilygorelik) [inline packages/nys-backtotop/src/nys-backtotop.mdx:75]: now that i think about it, we should add these events on the backtotop component, i know we dont have that now but can you please add them

File: packages/nys-alert/src/nys-alert.ts [hunk 3]
```diff
@@ -126,7 +126,7 @@ export class NysAlert extends LitElement {
      */
     this.dispatchEvent(
       new CustomEvent("nys-alert-closed", {
```
Comment (emilygorelik) [inline packages/nys-alert/src/nys-alert.ts:128]: what did we decide about the more than one hyphen syntax?

**Review by emilygorelik — CHANGES_REQUESTED** [review]
see comments

File: packages/nys-textarea/src/nys-textarea.ts (hunk 1 above)
Comment (NovaCat35) [reply packages/nys-textarea/src/nys-textarea.ts]: Added, but won't document. Discussed with Emily and holding this off for removal

File: templates/mdx.template.hbs [hunk 4]
```diff
@@ -95,15 +95,21 @@ The `nys-{{componentName}}` component emits the following events:
 2. `nys-focus`: Emitted when the {{componentName}} receives focus.
 3. `nys-blur`: Emitted when the {{componentName}} loses focus.
 
+**Event details** \
+The event’s `detail` object includes:
+- id (string): The id of the {{componentName}}.
+- checked (boolean): Whether the toggle is currently checked.
```
Comment (emilygorelik) [inline templates/mdx.template.hbs:101]: here too

**Review by esteinborn — APPROVED** [review]
LGTM
